%K activation
close all
clear all



[exc,cmd,si] =get_td_sweeps_200b('200bVC_activation-c6ttx4ap-0-24901660.tdms');
plot(exc)
figure
cmd = cmd - 70;%adjust for holding pot
plot(cmd)

Ik = exc(280/si,:);
Vk = cmd(280/si,:);

plot(Vk,Ik,'.')
title('I/V')

Gk = max(exc(round(300.5/si):round(301/si),:));
Gk = Gk/max(Gk);

[fitresult, gof] = createFit(Vk, Gk)

% 
% figure
% plot(fitresult,Vk,Gk)
% title('G/Gmax')


function [fitresult, gof] = createFit(Vk, Gk)
%CREATEFIT(VK,GK)
%  Create a fit.
%
%  Data for 'boltzFit' fit:
%      X Input : Vk
%      Y Output: Gk
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jun-2018 22:18:51


%% Fit: 'boltzFit'.
[xData, yData] = prepareCurveData( Vk, Gk );

% Set up fittype and options.
ft = fittype( 'a+ (b-a)/(1+ exp((v50-x)/z))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.915440926416632 0.463243347604601 0.913375856139019 0.63235924622541];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'boltzFit' );
h = plot( fitresult, xData, yData );
legend( h, 'Gk vs. Vk', 'boltzFit', 'Location', 'NorthEast' );
% Label axes
xlabel Vk
ylabel Gk
grid on
end




